export default function Paragraph() {
  return (
    <div className="container max-w-screen-sm">
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo necessitatibus sit officia voluptates perspiciatis saepe est, sapiente suscipit id. Optio dicta reiciendis dignissimos sunt et tenetur eos cupiditate nobis dolorum. Quas aliquid reprehenderit sed cum laborum necessitatibus sint odio veritatis voluptate vitae deserunt est, error excepturi neque fugit quisquam consectetur expedita. Ipsam voluptas molestias animi cum, eveniet sint magni nobis expedita. Rerum libero quam consequatur, inventore adipisci omnis ipsam voluptatem illo labore ratione consequuntur! Velit nam voluptatem assumenda excepturi enim itaque ab odit. Earum numquam quo possimus aspernatur nam facilis facere, dolor, magni similique tempore illo consequuntur consectetur in quis excepturi maiores veniam hic architecto quisquam laboriosam cum. Sed at eveniet neque perspiciatis aliquid tempore consequatur sunt id! Aliquam hic voluptas, libero laboriosam adipisci delectus earum! Dolore veniam qui in, magnam sequi quia architecto. Minima qui, blanditiis, sapiente sed nobis aut, doloremque omnis quam dolores consequuntur eum corporis placeat reiciendis!</p>
      <p className="pt-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui dolorum accusantium modi ut eligendi cupiditate fuga rerum fugit, tempora placeat amet est illo incidunt optio laborum? Dolor id magnam nemo? Molestias obcaecati natus quis odio reprehenderit iure cum, adipisci veniam a qui harum sed optio enim repudiandae unde nulla impedit deserunt itaque! Dignissimos porro beatae ad eum asperiores, temporibus vero rerum magnam et non error vel ut aliquam animi delectus tempora voluptatum iure sequi cupiditate, hic officia quibusdam voluptatem minus? Voluptatem, earum exercitationem? Corporis incidunt dolorem rem nihil sint, tempore assumenda at sapiente quia?</p>
      <p className="pt-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro a hic accusamus, eum enim ipsa eaque officia inventore fugit tempora excepturi voluptas neque tempore ab iure. Temporibus nihil libero incidunt perferendis sunt nobis facere in, ipsam odio, ipsa necessitatibus doloribus magni alias accusamus nostrum! Culpa ratione veritatis eaque. Repellat porro, rem eaque fuga sed ratione nesciunt fugiat illum quia suscipit ipsam nostrum quam sit sint reiciendis modi quos quis ut blanditiis consequatur provident error laudantium! Quaerat neque rem debitis illo voluptates nulla consequuntur quod consectetur omnis eius ipsum impedit, possimus temporibus nobis explicabo praesentium officia placeat ab, a tenetur cumque! Dolores placeat aliquid doloremque adipisci minus?</p>
    </div>
  )
}
